// flow-typed signature: 329a10d299e7c1b3c972407050571a34
// flow-typed version: <<STUB>>/multitab-singleton_v0.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multitab-singleton'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multitab-singleton' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multitab-singleton/dist/index' {
  declare module.exports: any;
}

declare module 'multitab-singleton/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multitab-singleton/dist/index.js' {
  declare module.exports: $Exports<'multitab-singleton/dist/index'>;
}
declare module 'multitab-singleton/src/index.js' {
  declare module.exports: $Exports<'multitab-singleton/src/index'>;
}
